---
- name: Verify
  hosts: all

  tasks:
    - name: set locale
      shell: export LANGUAGE=en_US.UTF-8 && export LC_ALL=en_US.UTF-8 && export LANG=en_US.UTF-8 && export LC_CTYPE=en_US.UTF-8

    - name: get return code for anki -h
      command: anki -h
      register: anki

    - name: Verify Anki is installed.
      assert:
        that:
          - anki.rc == 0
        success_msg: "Anki is installed."
        fail_msg: "Anki is not installed."
